### ISSUE TITLE
Wrong linking when in a Markdown (indexing) file we have content outside the link

### ISSUE THREAD

**Issue by thiblahute** [MathieuDuponchelle/hotdoc#14]
In https://git.collabora.com/cgit/user/tsaunier/gst-editing-service/.git/diff/docs/ges/md/GStreamer_Editing_Services_Overview.markdown?h=hotdoc

if I replace

```
#### [architecture](architecture.markdown)
```
with

```
#### [Architecture](architecture.markdown) - an high level overview of the various componenents of GES
```
In the documentation when I click on the link, it tries to redirect me to `architecture.markdown` and not `architecture.html` moreover, architecture.html has not been generated

**Comment by MathieuDuponchelle** [comment]
Yep, that's pretty much intended in order to avoid replacing things I shouldn't replace I have restricted the syntax pretty drastically, maybe we can find a better solution for providing a short description, that way the formatter has more latitude on how to expose that info

**Comment by MathieuDuponchelle** [comment]
Ideally I'd like to be able to parse yaml headers but I don't think there's support for that in CommonMark :/

**Comment by MathieuDuponchelle** [comment]
Fixed, thanks
