### ISSUE TITLE
Private field are not hidden

### ISSUE THREAD

**Issue by thiblahute** [MathieuDuponchelle/hotdoc#20]
If you get my [hotodoc branch for GES](https://git.collabora.com/cgit/user/tsaunier/gst-editing-service/.git/log/?h=hotdoc) and build it, you will see that in `docs/ges/html/c/GESAsset.html` the GESAsset structure private fields are not hidden:

```
struct _GESAsset
{
  GObject parent;

  /*  */
  GESAssetPrivate *priv;

  /* Padding for API extension */
  gpointer _ges_reserved[GES_PADDING];
};
``` 

Though they have been [declared private](https://phabricator.freedesktop.org/diffusion/GES/browse/master/ges/ges-asset.h;a8aa0b8886b89573daf9ddb009df1442a9c0fa5b$59)

**Comment by thiblahute** [comment]
Actually I just noticed GESAsset is not parsed as an object, I can't see any reason why (properties are properly parsed etc...)

**Comment by MathieuDuponchelle** [comment]
Fixed, you sure love your whitespaces : P
