### ISSUE TITLE
Linking API 'entry point' from a standard markdown file fails

### ISSUE THREAD

**Issue by thiblahute** [MathieuDuponchelle/hotdoc#21]
In my  [hotodoc branch for GES](https://git.collabora.com/cgit/user/tsaunier/gst-editing-service/.git/log/?h=hotdoc) if I decide to [link the GESTimeline documentation from the `architecture.markdown` page](https://git.collabora.com/cgit/user/tsaunier/gst-editing-service/.git/commit/?h=hotdoc-linking-errors&id=4f7b062fb262f988e624944790d04438722e5e9a), the links in the documentation is screw up:

```
Instance description

[GESTimeline](The GES GError types.html#GESTimeline) is the central object for any multimedia timeline.

Contains a list of GESLayer which users should use to arrange the various clips through time.

The output type is determined by the GESTrack that are set on the [GESTimeline](The GES GError types.html#GESTimeline).

To save/load a timeline, you can use the ges_timeline_load_from_uri() and ges_timeline_save_to_uri() methods to use the default format. If you wish

Note that any change you make in the timeline will not actually be taken into account until you call the ges_timeline_commit method.
```

**Comment by thiblahute** [comment]
Btw I also tried to simply link to GESTimeline link:

```
### [GESTimeline](GESTimeline.markdown)
```

but it also fails.

**Comment by MathieuDuponchelle** [comment]
Fixed, you can link things that way: we like [ze timeline](GESTimeline) , thanks
