### ISSUE TITLE
GI class 'Short description' Markdown is not parsed

### ISSUE THREAD

**Issue by thiblahute** [MathieuDuponchelle/hotdoc#23]
In my  [hotodoc branch for GES](https://git.collabora.com/cgit/user/tsaunier/gst-editing-service/.git/log/?h=hotdoc) the GESLayer short desc looks like:

```
Sequence of GESClip at a `priority` in a #GESTimeline 
```

thus should look like

Sequence of GESClip at a `priority` in a [GESTimeline]()

But is actually put in plain text in the doc

**Comment by MathieuDuponchelle** [comment]
fixed by 18faeeb08079f70d84cfd7d780e3f22ed4eb6d83
