### ISSUE TITLE
Doesn't complain if index Markdown file doesn't exist

### ISSUE THREAD

**Issue by pwithnall** [MathieuDuponchelle/hotdoc#25]
When testing hotdoc on Walbottle, something like the following command doesn't throw an error for me; it just generates blank documentation (only `API_index.js`, `home.png` and `style.css` are output in the `html/c` directory).

```
hotdoc -i does/not/exist/index.markdown …
```

**Comment by MathieuDuponchelle** [comment]
Fixed by bcf79ce0e3f6e8da74a59cb8ba38b7bdfce802ba , thanks, good to see you start testing the tool. I'd like to assume that is the only problem you encountered but can't believe it to be the case, don't hesitate to open other issues :)

**Comment by pwithnall** [comment]
I found 30 minutes to give it a brief try last night, but ran out of time before I could get it working or debug why I get no output files. Branch (for Walbottle) is here if you want to investigate, otherwise I will file bugs when I get time to continue playing with it: https://git.collabora.com/cgit/user/pwith/walbottle.git/log/?h=hotdoc

**Comment by MathieuDuponchelle** [comment]
Hey, simple issue here, if you run the tool with DOC_DEBUG=3 make you'll see it more clearly, basically you need to do http://paste.fedoraproject.org/278481/44467567, listing of symbols in markdown files is done with their original name.

This raised a traceback too, I'll fix it later but I thought I'd share that to get you going. Thanks for reporting, please report other issues you may find (not here though :P)
