### ISSUE TITLE
No warning if zero symbols are found

### ISSUE THREAD

**Issue by pwithnall** [MathieuDuponchelle/hotdoc#30]
If hotdoc finds zero symbols when parsing the input C files, it should probably output a warning that something is wrong, rather than returning success.

**Comment by MathieuDuponchelle** [comment]
Fixed by 8be685f67e1c22dddf7686799d45f24a91731b7d afaiu :)

**Comment by MathieuDuponchelle** [comment]
2268dfb35b36a0444abfcff40cc7d87b918eacbd might help too.
