### ISSUE TITLE
Implement a RESTful server to wrap hotdoc's API

### ISSUE THREAD

**Issue by MathieuDuponchelle** [MathieuDuponchelle/hotdoc#38]
The first iteration of the server must handle retrieving raw and formatted comments for a given symbol unique name, modifying a raw comment and getting the new formatted version, and publishing the change.

I will use https://github.com/GNOME/glib/blob/master/glib/gvariant.c as an example

## Methods:

* GET raw_comments/symbol_id

    example : 
    ```
    GET raw_comments/g_variant_new_boolean
    ```

    result : 
    ```
    /**
     * g_variant_new_boolean:
     * @value: a #gboolean value
     *
     * Creates a new boolean #GVariant instance -- either %TRUE or %FALSE.
     *
     * Returns: (transfer none): a floating reference to a new boolean #GVariant instance
     *
     * Since: 2.24
     **/
    ```

* GET formatted_comments/symbol_id
    example:
    ```
    GET formatted_comments/g_variant_new_boolean
    ```

    result:
    ```html
<div class="refsect2">
	<a name=g_variant_new_boolean></a>
	<h3 class="method">
		<span class="entry">The <code>“g_variant_new_boolean”</code> method</span>
	</h3>
	<pre class="programlisting">
<a class="link" title=GVariant href=GVariant.html#GVariant>GVariant</a> *
g_variant_new_boolean (<a class="link" title=gboolean href=Basic_Types.html#gboolean>gboolean</a> value)</pre>

	<p>Creates a new boolean <a href="GVariant.html#GVariant">GVariant</a> instance -- either <a href="Standard_Macros.html#TRUE">TRUE</a> or <a href="Standard_Macros.html#FALSE">FALSE</a>.</p>

			<div class="refsect3">
			<h4>Parameters</h4>
			<table style="width:100%">
				<colgroup>
					<col class="parameters_name" style="width:20%" />
					<col class="parameters_description" style="width:60%" />
					<col class="parameters_annotations" style="width:20%" />
				</colgroup>
				<tbody>
											<tr>
		<td class="parameter_name">
		<p>
		<i>value:</i>
		</p>
	</td>
		<td class="parameter_description"><p><p>a <a href="Basic_Types.html#gboolean">gboolean</a> value</p>
</p></td>
<td style="text-align: left;">


</td>
</tr>

									</tbody>
			</table>
		</div>
	
			<div class="refsect3">
	<h4>Returns</h4>
	<p>a floating reference to a new boolean <a href="GVariant.html#GVariant">GVariant</a> instance</p>

</div>

<p>
		
<span class="annotation">[<acronym title="Don't free data after the code is done"><span class="acronym">transfer: none</span></acronym>]</span>

	</p>

	
	
			<p>
		Since		       			: 2.24
				</p>
	</div>
    ```

* PUT raw_comments/symbol_id {'raw_comment': new_comment}

No example here, suffice to say the PUT will not actually modify the database, but will reformat the symbol and return the result

* POST raw_comments/symbol_id {'raw_comment': new_comment}

This will trigger the commiting of a patch that will update the comment in the source code, and potentially queue a rebuilding of the documentation if the server has been instantiated with "instant gratification" on.

**Comment by pwithnall** [comment]
> * POST raw_comments/symbol_id {'raw_comment': new_comment}
>
> This will trigger the commiting of a patch that will update the comment in the source code, and potentially queue a rebuilding of the documentation if the server has been instantiated with "instant gratification" on.

How is authentication handled? What does the server do if there’s a conflict.

You could use the current git commit ID on the documentation branch as a HTTP ETag for detecting edit conflicts.

**Comment by MathieuDuponchelle** [comment]
Authentication will be handled using this : https://github.com/wooyek/flask-social-blueprint , because it builds on top of Flask-Login and Flask-security, and it is a modular (flask blueprint) and simple project, as opposed to flask-social and python-social-auth, which both come with their own paradigm and (in the case of python-social-auth) their pretty complex machinery. It handles google and github authentication, which are the two backends I think are relevant to what we're doing. It will be easy to handle "local" accounts too, but I will not enable this at first. I've got a pull request with two patches in there (https://github.com/wooyek/flask-social-blueprint/pull/12), I hope it will make it in soon as they are pretty simple.

As for conflicts, the risk of them will be mitigated by my "per-symbol" approach: two persons can edit different symbols in the same file and that will not cause conflicts, there will be no conflict either when both persons edit the same symbol, but if two persons edit the same symbol concurrentially, the last one to publish will overwrite the other one, my idea is that I will implement a mechanism to update the edit view with a "this symbol's comment" has changed message, which should disable the publish button, with an option to reload the comment, sounds good ?

To be honest I was thinking of implementing this in a second phase, but if you think it's critical I can work on this for that iteration.

**Comment by pwithnall** [comment]
> Authentication will be handled…

Seems fine. I was asking more in terms of the protocol-level design. I guess this means sending the OAuth fields in a normal `Authorization` header with each request once authorised.

> As for conflicts, …

I think that using ETags to detect the conflicts fits in well with your suggestion at the protocol level. It's the standard REST way of doing this, iirc.

> To be honest I was thinking of implementing this in a second phase, but if you think it's critical I can work on this for that iteration.

Punting on this for a little while is fine, but it should be included in the design from the beginning.

**Comment by MathieuDuponchelle** [comment]
The upstream for this is now https://github.com/MathieuDuponchelle/hotdoc_server
