### ISSUE TITLE
Missing API indexes

### ISSUE THREAD

**Issue by ndufresne** [MathieuDuponchelle/hotdoc#5]
API indexes include the global index, deprecated index, and all the index generated from the Since 1.X marks.

API Index
Index of deprecated API
Index of new API in 1.6
Index of new API in 1.4
Index of new API in 1.2.3
Index of new API in 1.2
Index of new API in 1.0.10
Index of new API in 1.0.5

**Comment by MathieuDuponchelle** [comment]
I'll get to that a bit later, thanks for reporting

**Comment by MathieuDuponchelle** [comment]
API indexes are now generated (all as one page, you can check the result at https://people.collabora.com/~meh/gst_doc_new/c/api_index.html).

Please open a new bug if you have remarks about the current solution.
