### ISSUE TITLE
python: Wrong links and "ignore_bullet_points: true" in the Object hierarchy page

### ISSUE THREAD

**Issue by tsaunier** [MathieuDuponchelle/hotdoc#7]
Page: https://people.collabora.com/~meh/gst_doc_new/gst_python/Object%20Hierarchy.html

Links are wrong and I can see 

```
ignore_bullet_points: true
```

as a 'title'

**Comment by MathieuDuponchelle** [comment]
Hm right that's because it was generated with CommonMark, I'll need to check how to convey this metadata in a portable manner

**Comment by MathieuDuponchelle** [comment]
This is now fixed, as hotdoc generates the inheritance graph itself, you can check the result at https://people.collabora.com/~meh/gst_doc_new/python/object_hierarchy.html .

Thanks for the report !
